// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TelemetryDataBuf.proto
package com.tyjw.inspectline.web.telemetry.common;

public final class TelemetryDataPB {
  private TelemetryDataPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TelemetryDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TelemetryData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *经度
     * </pre>
     *
     * <code>double lng = 1;</code>
     */
    double getLng();

    /**
     * <pre>
     *纬度
     * </pre>
     *
     * <code>double lat = 2;</code>
     */
    double getLat();

    /**
     * <pre>
     *海拔高度
     * </pre>
     *
     * <code>float altitude = 3;</code>
     */
    float getAltitude();

    /**
     * <pre>
     *相对高度
     * </pre>
     *
     * <code>float ultrasonic = 4;</code>
     */
    float getUltrasonic();

    /**
     * <pre>
     *俯仰角
     * </pre>
     *
     * <code>float pitch = 5;</code>
     */
    float getPitch();

    /**
     * <pre>
     *横滚角
     * </pre>
     *
     * <code>float roll = 6;</code>
     */
    float getRoll();

    /**
     * <pre>
     *航向角
     * </pre>
     *
     * <code>float yaw = 7;</code>
     */
    float getYaw();

    /**
     * <pre>
     *空速
     * </pre>
     *
     * <code>float airspeed = 8;</code>
     */
    float getAirspeed();

    /**
     * <pre>
     *地速
     * </pre>
     *
     * <code>float velocity = 9;</code>
     */
    float getVelocity();

    /**
     * <pre>
     *时间戳 UTC+8
     * </pre>
     *
     * <code>uint64 timestamp = 10;</code>
     */
    long getTimestamp();

    /**
     * <pre>
     *盒子编号
     * </pre>
     *
     * <code>string boxSn = 11;</code>
     */
    String getBoxSn();
    /**
     * <pre>
     *盒子编号
     * </pre>
     *
     * <code>string boxSn = 11;</code>
     */
    com.google.protobuf.ByteString
        getBoxSnBytes();
  }
  /**
   * Protobuf type {@code TelemetryData}
   */
  public  static final class TelemetryData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TelemetryData)
      TelemetryDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TelemetryData.newBuilder() to construct.
    private TelemetryData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TelemetryData() {
      lng_ = 0D;
      lat_ = 0D;
      altitude_ = 0F;
      ultrasonic_ = 0F;
      pitch_ = 0F;
      roll_ = 0F;
      yaw_ = 0F;
      airspeed_ = 0F;
      velocity_ = 0F;
      timestamp_ = 0L;
      boxSn_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TelemetryData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              lng_ = input.readDouble();
              break;
            }
            case 17: {

              lat_ = input.readDouble();
              break;
            }
            case 29: {

              altitude_ = input.readFloat();
              break;
            }
            case 37: {

              ultrasonic_ = input.readFloat();
              break;
            }
            case 45: {

              pitch_ = input.readFloat();
              break;
            }
            case 53: {

              roll_ = input.readFloat();
              break;
            }
            case 61: {

              yaw_ = input.readFloat();
              break;
            }
            case 69: {

              airspeed_ = input.readFloat();
              break;
            }
            case 77: {

              velocity_ = input.readFloat();
              break;
            }
            case 80: {

              timestamp_ = input.readUInt64();
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              boxSn_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TelemetryDataPB.internal_static_TelemetryData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TelemetryDataPB.internal_static_TelemetryData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TelemetryData.class, Builder.class);
    }

    public static final int LNG_FIELD_NUMBER = 1;
    private double lng_;
    /**
     * <pre>
     *经度
     * </pre>
     *
     * <code>double lng = 1;</code>
     */
    public double getLng() {
      return lng_;
    }

    public static final int LAT_FIELD_NUMBER = 2;
    private double lat_;
    /**
     * <pre>
     *纬度
     * </pre>
     *
     * <code>double lat = 2;</code>
     */
    public double getLat() {
      return lat_;
    }

    public static final int ALTITUDE_FIELD_NUMBER = 3;
    private float altitude_;
    /**
     * <pre>
     *海拔高度
     * </pre>
     *
     * <code>float altitude = 3;</code>
     */
    public float getAltitude() {
      return altitude_;
    }

    public static final int ULTRASONIC_FIELD_NUMBER = 4;
    private float ultrasonic_;
    /**
     * <pre>
     *相对高度
     * </pre>
     *
     * <code>float ultrasonic = 4;</code>
     */
    public float getUltrasonic() {
      return ultrasonic_;
    }

    public static final int PITCH_FIELD_NUMBER = 5;
    private float pitch_;
    /**
     * <pre>
     *俯仰角
     * </pre>
     *
     * <code>float pitch = 5;</code>
     */
    public float getPitch() {
      return pitch_;
    }

    public static final int ROLL_FIELD_NUMBER = 6;
    private float roll_;
    /**
     * <pre>
     *横滚角
     * </pre>
     *
     * <code>float roll = 6;</code>
     */
    public float getRoll() {
      return roll_;
    }

    public static final int YAW_FIELD_NUMBER = 7;
    private float yaw_;
    /**
     * <pre>
     *航向角
     * </pre>
     *
     * <code>float yaw = 7;</code>
     */
    public float getYaw() {
      return yaw_;
    }

    public static final int AIRSPEED_FIELD_NUMBER = 8;
    private float airspeed_;
    /**
     * <pre>
     *空速
     * </pre>
     *
     * <code>float airspeed = 8;</code>
     */
    public float getAirspeed() {
      return airspeed_;
    }

    public static final int VELOCITY_FIELD_NUMBER = 9;
    private float velocity_;
    /**
     * <pre>
     *地速
     * </pre>
     *
     * <code>float velocity = 9;</code>
     */
    public float getVelocity() {
      return velocity_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 10;
    private long timestamp_;
    /**
     * <pre>
     *时间戳 UTC+8
     * </pre>
     *
     * <code>uint64 timestamp = 10;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int BOXSN_FIELD_NUMBER = 11;
    private volatile Object boxSn_;
    /**
     * <pre>
     *盒子编号
     * </pre>
     *
     * <code>string boxSn = 11;</code>
     */
    public String getBoxSn() {
      Object ref = boxSn_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        boxSn_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *盒子编号
     * </pre>
     *
     * <code>string boxSn = 11;</code>
     */
    public com.google.protobuf.ByteString
        getBoxSnBytes() {
      Object ref = boxSn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        boxSn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (lng_ != 0D) {
        output.writeDouble(1, lng_);
      }
      if (lat_ != 0D) {
        output.writeDouble(2, lat_);
      }
      if (altitude_ != 0F) {
        output.writeFloat(3, altitude_);
      }
      if (ultrasonic_ != 0F) {
        output.writeFloat(4, ultrasonic_);
      }
      if (pitch_ != 0F) {
        output.writeFloat(5, pitch_);
      }
      if (roll_ != 0F) {
        output.writeFloat(6, roll_);
      }
      if (yaw_ != 0F) {
        output.writeFloat(7, yaw_);
      }
      if (airspeed_ != 0F) {
        output.writeFloat(8, airspeed_);
      }
      if (velocity_ != 0F) {
        output.writeFloat(9, velocity_);
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(10, timestamp_);
      }
      if (!getBoxSnBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, boxSn_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (lng_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, lng_);
      }
      if (lat_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, lat_);
      }
      if (altitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, altitude_);
      }
      if (ultrasonic_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, ultrasonic_);
      }
      if (pitch_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, pitch_);
      }
      if (roll_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, roll_);
      }
      if (yaw_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, yaw_);
      }
      if (airspeed_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, airspeed_);
      }
      if (velocity_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, velocity_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(10, timestamp_);
      }
      if (!getBoxSnBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, boxSn_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TelemetryData)) {
        return super.equals(obj);
      }
      TelemetryData other = (TelemetryData) obj;

      boolean result = true;
      result = result && (
          Double.doubleToLongBits(getLng())
          == Double.doubleToLongBits(
              other.getLng()));
      result = result && (
          Double.doubleToLongBits(getLat())
          == Double.doubleToLongBits(
              other.getLat()));
      result = result && (
          Float.floatToIntBits(getAltitude())
          == Float.floatToIntBits(
              other.getAltitude()));
      result = result && (
          Float.floatToIntBits(getUltrasonic())
          == Float.floatToIntBits(
              other.getUltrasonic()));
      result = result && (
          Float.floatToIntBits(getPitch())
          == Float.floatToIntBits(
              other.getPitch()));
      result = result && (
          Float.floatToIntBits(getRoll())
          == Float.floatToIntBits(
              other.getRoll()));
      result = result && (
          Float.floatToIntBits(getYaw())
          == Float.floatToIntBits(
              other.getYaw()));
      result = result && (
          Float.floatToIntBits(getAirspeed())
          == Float.floatToIntBits(
              other.getAirspeed()));
      result = result && (
          Float.floatToIntBits(getVelocity())
          == Float.floatToIntBits(
              other.getVelocity()));
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getBoxSn()
          .equals(other.getBoxSn());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LNG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLng()));
      hash = (37 * hash) + LAT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLat()));
      hash = (37 * hash) + ALTITUDE_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getAltitude());
      hash = (37 * hash) + ULTRASONIC_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getUltrasonic());
      hash = (37 * hash) + PITCH_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getPitch());
      hash = (37 * hash) + ROLL_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getRoll());
      hash = (37 * hash) + YAW_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getYaw());
      hash = (37 * hash) + AIRSPEED_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getAirspeed());
      hash = (37 * hash) + VELOCITY_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getVelocity());
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + BOXSN_FIELD_NUMBER;
      hash = (53 * hash) + getBoxSn().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TelemetryData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TelemetryData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TelemetryData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TelemetryData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TelemetryData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TelemetryData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TelemetryData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TelemetryData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TelemetryData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TelemetryData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TelemetryData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TelemetryData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TelemetryData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TelemetryData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TelemetryData)
        TelemetryDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TelemetryDataPB.internal_static_TelemetryData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TelemetryDataPB.internal_static_TelemetryData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TelemetryData.class, Builder.class);
      }

      // Construct using TelemetryDataPB.TelemetryData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        lng_ = 0D;

        lat_ = 0D;

        altitude_ = 0F;

        ultrasonic_ = 0F;

        pitch_ = 0F;

        roll_ = 0F;

        yaw_ = 0F;

        airspeed_ = 0F;

        velocity_ = 0F;

        timestamp_ = 0L;

        boxSn_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TelemetryDataPB.internal_static_TelemetryData_descriptor;
      }

      public TelemetryData getDefaultInstanceForType() {
        return TelemetryData.getDefaultInstance();
      }

      public TelemetryData build() {
        TelemetryData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TelemetryData buildPartial() {
        TelemetryData result = new TelemetryData(this);
        result.lng_ = lng_;
        result.lat_ = lat_;
        result.altitude_ = altitude_;
        result.ultrasonic_ = ultrasonic_;
        result.pitch_ = pitch_;
        result.roll_ = roll_;
        result.yaw_ = yaw_;
        result.airspeed_ = airspeed_;
        result.velocity_ = velocity_;
        result.timestamp_ = timestamp_;
        result.boxSn_ = boxSn_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TelemetryData) {
          return mergeFrom((TelemetryData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TelemetryData other) {
        if (other == TelemetryData.getDefaultInstance()) return this;
        if (other.getLng() != 0D) {
          setLng(other.getLng());
        }
        if (other.getLat() != 0D) {
          setLat(other.getLat());
        }
        if (other.getAltitude() != 0F) {
          setAltitude(other.getAltitude());
        }
        if (other.getUltrasonic() != 0F) {
          setUltrasonic(other.getUltrasonic());
        }
        if (other.getPitch() != 0F) {
          setPitch(other.getPitch());
        }
        if (other.getRoll() != 0F) {
          setRoll(other.getRoll());
        }
        if (other.getYaw() != 0F) {
          setYaw(other.getYaw());
        }
        if (other.getAirspeed() != 0F) {
          setAirspeed(other.getAirspeed());
        }
        if (other.getVelocity() != 0F) {
          setVelocity(other.getVelocity());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getBoxSn().isEmpty()) {
          boxSn_ = other.boxSn_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TelemetryData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TelemetryData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double lng_ ;
      /**
       * <pre>
       *经度
       * </pre>
       *
       * <code>double lng = 1;</code>
       */
      public double getLng() {
        return lng_;
      }
      /**
       * <pre>
       *经度
       * </pre>
       *
       * <code>double lng = 1;</code>
       */
      public Builder setLng(double value) {
        
        lng_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *经度
       * </pre>
       *
       * <code>double lng = 1;</code>
       */
      public Builder clearLng() {
        
        lng_ = 0D;
        onChanged();
        return this;
      }

      private double lat_ ;
      /**
       * <pre>
       *纬度
       * </pre>
       *
       * <code>double lat = 2;</code>
       */
      public double getLat() {
        return lat_;
      }
      /**
       * <pre>
       *纬度
       * </pre>
       *
       * <code>double lat = 2;</code>
       */
      public Builder setLat(double value) {
        
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *纬度
       * </pre>
       *
       * <code>double lat = 2;</code>
       */
      public Builder clearLat() {
        
        lat_ = 0D;
        onChanged();
        return this;
      }

      private float altitude_ ;
      /**
       * <pre>
       *海拔高度
       * </pre>
       *
       * <code>float altitude = 3;</code>
       */
      public float getAltitude() {
        return altitude_;
      }
      /**
       * <pre>
       *海拔高度
       * </pre>
       *
       * <code>float altitude = 3;</code>
       */
      public Builder setAltitude(float value) {
        
        altitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *海拔高度
       * </pre>
       *
       * <code>float altitude = 3;</code>
       */
      public Builder clearAltitude() {
        
        altitude_ = 0F;
        onChanged();
        return this;
      }

      private float ultrasonic_ ;
      /**
       * <pre>
       *相对高度
       * </pre>
       *
       * <code>float ultrasonic = 4;</code>
       */
      public float getUltrasonic() {
        return ultrasonic_;
      }
      /**
       * <pre>
       *相对高度
       * </pre>
       *
       * <code>float ultrasonic = 4;</code>
       */
      public Builder setUltrasonic(float value) {
        
        ultrasonic_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *相对高度
       * </pre>
       *
       * <code>float ultrasonic = 4;</code>
       */
      public Builder clearUltrasonic() {
        
        ultrasonic_ = 0F;
        onChanged();
        return this;
      }

      private float pitch_ ;
      /**
       * <pre>
       *俯仰角
       * </pre>
       *
       * <code>float pitch = 5;</code>
       */
      public float getPitch() {
        return pitch_;
      }
      /**
       * <pre>
       *俯仰角
       * </pre>
       *
       * <code>float pitch = 5;</code>
       */
      public Builder setPitch(float value) {
        
        pitch_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *俯仰角
       * </pre>
       *
       * <code>float pitch = 5;</code>
       */
      public Builder clearPitch() {
        
        pitch_ = 0F;
        onChanged();
        return this;
      }

      private float roll_ ;
      /**
       * <pre>
       *横滚角
       * </pre>
       *
       * <code>float roll = 6;</code>
       */
      public float getRoll() {
        return roll_;
      }
      /**
       * <pre>
       *横滚角
       * </pre>
       *
       * <code>float roll = 6;</code>
       */
      public Builder setRoll(float value) {
        
        roll_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *横滚角
       * </pre>
       *
       * <code>float roll = 6;</code>
       */
      public Builder clearRoll() {
        
        roll_ = 0F;
        onChanged();
        return this;
      }

      private float yaw_ ;
      /**
       * <pre>
       *航向角
       * </pre>
       *
       * <code>float yaw = 7;</code>
       */
      public float getYaw() {
        return yaw_;
      }
      /**
       * <pre>
       *航向角
       * </pre>
       *
       * <code>float yaw = 7;</code>
       */
      public Builder setYaw(float value) {
        
        yaw_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *航向角
       * </pre>
       *
       * <code>float yaw = 7;</code>
       */
      public Builder clearYaw() {
        
        yaw_ = 0F;
        onChanged();
        return this;
      }

      private float airspeed_ ;
      /**
       * <pre>
       *空速
       * </pre>
       *
       * <code>float airspeed = 8;</code>
       */
      public float getAirspeed() {
        return airspeed_;
      }
      /**
       * <pre>
       *空速
       * </pre>
       *
       * <code>float airspeed = 8;</code>
       */
      public Builder setAirspeed(float value) {
        
        airspeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *空速
       * </pre>
       *
       * <code>float airspeed = 8;</code>
       */
      public Builder clearAirspeed() {
        
        airspeed_ = 0F;
        onChanged();
        return this;
      }

      private float velocity_ ;
      /**
       * <pre>
       *地速
       * </pre>
       *
       * <code>float velocity = 9;</code>
       */
      public float getVelocity() {
        return velocity_;
      }
      /**
       * <pre>
       *地速
       * </pre>
       *
       * <code>float velocity = 9;</code>
       */
      public Builder setVelocity(float value) {
        
        velocity_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *地速
       * </pre>
       *
       * <code>float velocity = 9;</code>
       */
      public Builder clearVelocity() {
        
        velocity_ = 0F;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       *时间戳 UTC+8
       * </pre>
       *
       * <code>uint64 timestamp = 10;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       *时间戳 UTC+8
       * </pre>
       *
       * <code>uint64 timestamp = 10;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳 UTC+8
       * </pre>
       *
       * <code>uint64 timestamp = 10;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private Object boxSn_ = "";
      /**
       * <pre>
       *盒子编号
       * </pre>
       *
       * <code>string boxSn = 11;</code>
       */
      public String getBoxSn() {
        Object ref = boxSn_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          boxSn_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *盒子编号
       * </pre>
       *
       * <code>string boxSn = 11;</code>
       */
      public com.google.protobuf.ByteString
          getBoxSnBytes() {
        Object ref = boxSn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          boxSn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *盒子编号
       * </pre>
       *
       * <code>string boxSn = 11;</code>
       */
      public Builder setBoxSn(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        boxSn_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *盒子编号
       * </pre>
       *
       * <code>string boxSn = 11;</code>
       */
      public Builder clearBoxSn() {
        
        boxSn_ = getDefaultInstance().getBoxSn();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *盒子编号
       * </pre>
       *
       * <code>string boxSn = 11;</code>
       */
      public Builder setBoxSnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        boxSn_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TelemetryData)
    }

    // @@protoc_insertion_point(class_scope:TelemetryData)
    private static final TelemetryData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TelemetryData();
    }

    public static TelemetryData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TelemetryData>
        PARSER = new com.google.protobuf.AbstractParser<TelemetryData>() {
      public TelemetryData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TelemetryData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TelemetryData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TelemetryData> getParserForType() {
      return PARSER;
    }

    public TelemetryData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlanLineDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlanLineData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *结束航线后动作：1返航，2原地悬停，3原地降落
     * </pre>
     *
     * <code>uint32 finishedAction = 1;</code>
     */
    int getFinishedAction();

    /**
     * <pre>
     *最大飞行速度
     * </pre>
     *
     * <code>float maxSpeed = 2;</code>
     */
    float getMaxSpeed();

    /**
     * <pre>
     *自动飞行速度
     * </pre>
     *
     * <code>float autoSpeed = 3;</code>
     */
    float getAutoSpeed();

    /**
     * <pre>
     *坐标点数组
     * </pre>
     *
     * <code>repeated .PointData points = 4;</code>
     */
    java.util.List<PointData>
        getPointsList();
    /**
     * <pre>
     *坐标点数组
     * </pre>
     *
     * <code>repeated .PointData points = 4;</code>
     */
    PointData getPoints(int index);
    /**
     * <pre>
     *坐标点数组
     * </pre>
     *
     * <code>repeated .PointData points = 4;</code>
     */
    int getPointsCount();
    /**
     * <pre>
     *坐标点数组
     * </pre>
     *
     * <code>repeated .PointData points = 4;</code>
     */
    java.util.List<? extends PointDataOrBuilder>
        getPointsOrBuilderList();
    /**
     * <pre>
     *坐标点数组
     * </pre>
     *
     * <code>repeated .PointData points = 4;</code>
     */
    PointDataOrBuilder getPointsOrBuilder(
			int index);
  }
  /**
   * Protobuf type {@code PlanLineData}
   */
  public  static final class PlanLineData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlanLineData)
      PlanLineDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlanLineData.newBuilder() to construct.
    private PlanLineData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlanLineData() {
      finishedAction_ = 0;
      maxSpeed_ = 0F;
      autoSpeed_ = 0F;
      points_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlanLineData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              finishedAction_ = input.readUInt32();
              break;
            }
            case 21: {

              maxSpeed_ = input.readFloat();
              break;
            }
            case 29: {

              autoSpeed_ = input.readFloat();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                points_ = new java.util.ArrayList<PointData>();
                mutable_bitField0_ |= 0x00000008;
              }
              points_.add(
                  input.readMessage(PointData.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          points_ = java.util.Collections.unmodifiableList(points_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TelemetryDataPB.internal_static_PlanLineData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TelemetryDataPB.internal_static_PlanLineData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PlanLineData.class, Builder.class);
    }

    private int bitField0_;
    public static final int FINISHEDACTION_FIELD_NUMBER = 1;
    private int finishedAction_;
    /**
     * <pre>
     *结束航线后动作：1返航，2原地悬停，3原地降落
     * </pre>
     *
     * <code>uint32 finishedAction = 1;</code>
     */
    public int getFinishedAction() {
      return finishedAction_;
    }

    public static final int MAXSPEED_FIELD_NUMBER = 2;
    private float maxSpeed_;
    /**
     * <pre>
     *最大飞行速度
     * </pre>
     *
     * <code>float maxSpeed = 2;</code>
     */
    public float getMaxSpeed() {
      return maxSpeed_;
    }

    public static final int AUTOSPEED_FIELD_NUMBER = 3;
    private float autoSpeed_;
    /**
     * <pre>
     *自动飞行速度
     * </pre>
     *
     * <code>float autoSpeed = 3;</code>
     */
    public float getAutoSpeed() {
      return autoSpeed_;
    }

    public static final int POINTS_FIELD_NUMBER = 4;
    private java.util.List<PointData> points_;
    /**
     * <pre>
     *坐标点数组
     * </pre>
     *
     * <code>repeated .PointData points = 4;</code>
     */
    public java.util.List<PointData> getPointsList() {
      return points_;
    }
    /**
     * <pre>
     *坐标点数组
     * </pre>
     *
     * <code>repeated .PointData points = 4;</code>
     */
    public java.util.List<? extends PointDataOrBuilder>
        getPointsOrBuilderList() {
      return points_;
    }
    /**
     * <pre>
     *坐标点数组
     * </pre>
     *
     * <code>repeated .PointData points = 4;</code>
     */
    public int getPointsCount() {
      return points_.size();
    }
    /**
     * <pre>
     *坐标点数组
     * </pre>
     *
     * <code>repeated .PointData points = 4;</code>
     */
    public PointData getPoints(int index) {
      return points_.get(index);
    }
    /**
     * <pre>
     *坐标点数组
     * </pre>
     *
     * <code>repeated .PointData points = 4;</code>
     */
    public PointDataOrBuilder getPointsOrBuilder(
        int index) {
      return points_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (finishedAction_ != 0) {
        output.writeUInt32(1, finishedAction_);
      }
      if (maxSpeed_ != 0F) {
        output.writeFloat(2, maxSpeed_);
      }
      if (autoSpeed_ != 0F) {
        output.writeFloat(3, autoSpeed_);
      }
      for (int i = 0; i < points_.size(); i++) {
        output.writeMessage(4, points_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (finishedAction_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, finishedAction_);
      }
      if (maxSpeed_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, maxSpeed_);
      }
      if (autoSpeed_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, autoSpeed_);
      }
      for (int i = 0; i < points_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, points_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PlanLineData)) {
        return super.equals(obj);
      }
      PlanLineData other = (PlanLineData) obj;

      boolean result = true;
      result = result && (getFinishedAction()
          == other.getFinishedAction());
      result = result && (
          Float.floatToIntBits(getMaxSpeed())
          == Float.floatToIntBits(
              other.getMaxSpeed()));
      result = result && (
          Float.floatToIntBits(getAutoSpeed())
          == Float.floatToIntBits(
              other.getAutoSpeed()));
      result = result && getPointsList()
          .equals(other.getPointsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FINISHEDACTION_FIELD_NUMBER;
      hash = (53 * hash) + getFinishedAction();
      hash = (37 * hash) + MAXSPEED_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getMaxSpeed());
      hash = (37 * hash) + AUTOSPEED_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getAutoSpeed());
      if (getPointsCount() > 0) {
        hash = (37 * hash) + POINTS_FIELD_NUMBER;
        hash = (53 * hash) + getPointsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PlanLineData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlanLineData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlanLineData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlanLineData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlanLineData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlanLineData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlanLineData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlanLineData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlanLineData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PlanLineData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlanLineData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlanLineData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PlanLineData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlanLineData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlanLineData)
        PlanLineDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TelemetryDataPB.internal_static_PlanLineData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TelemetryDataPB.internal_static_PlanLineData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PlanLineData.class, Builder.class);
      }

      // Construct using TelemetryDataPB.PlanLineData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPointsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        finishedAction_ = 0;

        maxSpeed_ = 0F;

        autoSpeed_ = 0F;

        if (pointsBuilder_ == null) {
          points_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          pointsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TelemetryDataPB.internal_static_PlanLineData_descriptor;
      }

      public PlanLineData getDefaultInstanceForType() {
        return PlanLineData.getDefaultInstance();
      }

      public PlanLineData build() {
        PlanLineData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PlanLineData buildPartial() {
        PlanLineData result = new PlanLineData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.finishedAction_ = finishedAction_;
        result.maxSpeed_ = maxSpeed_;
        result.autoSpeed_ = autoSpeed_;
        if (pointsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            points_ = java.util.Collections.unmodifiableList(points_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.points_ = points_;
        } else {
          result.points_ = pointsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PlanLineData) {
          return mergeFrom((PlanLineData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PlanLineData other) {
        if (other == PlanLineData.getDefaultInstance()) return this;
        if (other.getFinishedAction() != 0) {
          setFinishedAction(other.getFinishedAction());
        }
        if (other.getMaxSpeed() != 0F) {
          setMaxSpeed(other.getMaxSpeed());
        }
        if (other.getAutoSpeed() != 0F) {
          setAutoSpeed(other.getAutoSpeed());
        }
        if (pointsBuilder_ == null) {
          if (!other.points_.isEmpty()) {
            if (points_.isEmpty()) {
              points_ = other.points_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensurePointsIsMutable();
              points_.addAll(other.points_);
            }
            onChanged();
          }
        } else {
          if (!other.points_.isEmpty()) {
            if (pointsBuilder_.isEmpty()) {
              pointsBuilder_.dispose();
              pointsBuilder_ = null;
              points_ = other.points_;
              bitField0_ = (bitField0_ & ~0x00000008);
              pointsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPointsFieldBuilder() : null;
            } else {
              pointsBuilder_.addAllMessages(other.points_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PlanLineData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PlanLineData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int finishedAction_ ;
      /**
       * <pre>
       *结束航线后动作：1返航，2原地悬停，3原地降落
       * </pre>
       *
       * <code>uint32 finishedAction = 1;</code>
       */
      public int getFinishedAction() {
        return finishedAction_;
      }
      /**
       * <pre>
       *结束航线后动作：1返航，2原地悬停，3原地降落
       * </pre>
       *
       * <code>uint32 finishedAction = 1;</code>
       */
      public Builder setFinishedAction(int value) {
        
        finishedAction_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *结束航线后动作：1返航，2原地悬停，3原地降落
       * </pre>
       *
       * <code>uint32 finishedAction = 1;</code>
       */
      public Builder clearFinishedAction() {
        
        finishedAction_ = 0;
        onChanged();
        return this;
      }

      private float maxSpeed_ ;
      /**
       * <pre>
       *最大飞行速度
       * </pre>
       *
       * <code>float maxSpeed = 2;</code>
       */
      public float getMaxSpeed() {
        return maxSpeed_;
      }
      /**
       * <pre>
       *最大飞行速度
       * </pre>
       *
       * <code>float maxSpeed = 2;</code>
       */
      public Builder setMaxSpeed(float value) {
        
        maxSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *最大飞行速度
       * </pre>
       *
       * <code>float maxSpeed = 2;</code>
       */
      public Builder clearMaxSpeed() {
        
        maxSpeed_ = 0F;
        onChanged();
        return this;
      }

      private float autoSpeed_ ;
      /**
       * <pre>
       *自动飞行速度
       * </pre>
       *
       * <code>float autoSpeed = 3;</code>
       */
      public float getAutoSpeed() {
        return autoSpeed_;
      }
      /**
       * <pre>
       *自动飞行速度
       * </pre>
       *
       * <code>float autoSpeed = 3;</code>
       */
      public Builder setAutoSpeed(float value) {
        
        autoSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *自动飞行速度
       * </pre>
       *
       * <code>float autoSpeed = 3;</code>
       */
      public Builder clearAutoSpeed() {
        
        autoSpeed_ = 0F;
        onChanged();
        return this;
      }

      private java.util.List<PointData> points_ =
        java.util.Collections.emptyList();
      private void ensurePointsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          points_ = new java.util.ArrayList<PointData>(points_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PointData, PointData.Builder, PointDataOrBuilder> pointsBuilder_;

      /**
       * <pre>
       *坐标点数组
       * </pre>
       *
       * <code>repeated .PointData points = 4;</code>
       */
      public java.util.List<PointData> getPointsList() {
        if (pointsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(points_);
        } else {
          return pointsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *坐标点数组
       * </pre>
       *
       * <code>repeated .PointData points = 4;</code>
       */
      public int getPointsCount() {
        if (pointsBuilder_ == null) {
          return points_.size();
        } else {
          return pointsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *坐标点数组
       * </pre>
       *
       * <code>repeated .PointData points = 4;</code>
       */
      public PointData getPoints(int index) {
        if (pointsBuilder_ == null) {
          return points_.get(index);
        } else {
          return pointsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *坐标点数组
       * </pre>
       *
       * <code>repeated .PointData points = 4;</code>
       */
      public Builder setPoints(
          int index, PointData value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.set(index, value);
          onChanged();
        } else {
          pointsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *坐标点数组
       * </pre>
       *
       * <code>repeated .PointData points = 4;</code>
       */
      public Builder setPoints(
          int index, PointData.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.set(index, builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *坐标点数组
       * </pre>
       *
       * <code>repeated .PointData points = 4;</code>
       */
      public Builder addPoints(PointData value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.add(value);
          onChanged();
        } else {
          pointsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *坐标点数组
       * </pre>
       *
       * <code>repeated .PointData points = 4;</code>
       */
      public Builder addPoints(
          int index, PointData value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.add(index, value);
          onChanged();
        } else {
          pointsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *坐标点数组
       * </pre>
       *
       * <code>repeated .PointData points = 4;</code>
       */
      public Builder addPoints(
          PointData.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.add(builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *坐标点数组
       * </pre>
       *
       * <code>repeated .PointData points = 4;</code>
       */
      public Builder addPoints(
          int index, PointData.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.add(index, builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *坐标点数组
       * </pre>
       *
       * <code>repeated .PointData points = 4;</code>
       */
      public Builder addAllPoints(
          Iterable<? extends PointData> values) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, points_);
          onChanged();
        } else {
          pointsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *坐标点数组
       * </pre>
       *
       * <code>repeated .PointData points = 4;</code>
       */
      public Builder clearPoints() {
        if (pointsBuilder_ == null) {
          points_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          pointsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *坐标点数组
       * </pre>
       *
       * <code>repeated .PointData points = 4;</code>
       */
      public Builder removePoints(int index) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.remove(index);
          onChanged();
        } else {
          pointsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *坐标点数组
       * </pre>
       *
       * <code>repeated .PointData points = 4;</code>
       */
      public PointData.Builder getPointsBuilder(
          int index) {
        return getPointsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *坐标点数组
       * </pre>
       *
       * <code>repeated .PointData points = 4;</code>
       */
      public PointDataOrBuilder getPointsOrBuilder(
          int index) {
        if (pointsBuilder_ == null) {
          return points_.get(index);  } else {
          return pointsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *坐标点数组
       * </pre>
       *
       * <code>repeated .PointData points = 4;</code>
       */
      public java.util.List<? extends PointDataOrBuilder>
           getPointsOrBuilderList() {
        if (pointsBuilder_ != null) {
          return pointsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(points_);
        }
      }
      /**
       * <pre>
       *坐标点数组
       * </pre>
       *
       * <code>repeated .PointData points = 4;</code>
       */
      public PointData.Builder addPointsBuilder() {
        return getPointsFieldBuilder().addBuilder(
            PointData.getDefaultInstance());
      }
      /**
       * <pre>
       *坐标点数组
       * </pre>
       *
       * <code>repeated .PointData points = 4;</code>
       */
      public PointData.Builder addPointsBuilder(
          int index) {
        return getPointsFieldBuilder().addBuilder(
            index, PointData.getDefaultInstance());
      }
      /**
       * <pre>
       *坐标点数组
       * </pre>
       *
       * <code>repeated .PointData points = 4;</code>
       */
      public java.util.List<PointData.Builder>
           getPointsBuilderList() {
        return getPointsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PointData, PointData.Builder, PointDataOrBuilder>
          getPointsFieldBuilder() {
        if (pointsBuilder_ == null) {
          pointsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PointData, PointData.Builder, PointDataOrBuilder>(
                  points_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          points_ = null;
        }
        return pointsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PlanLineData)
    }

    // @@protoc_insertion_point(class_scope:PlanLineData)
    private static final PlanLineData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PlanLineData();
    }

    public static PlanLineData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlanLineData>
        PARSER = new com.google.protobuf.AbstractParser<PlanLineData>() {
      public PlanLineData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PlanLineData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlanLineData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PlanLineData> getParserForType() {
      return PARSER;
    }

    public PlanLineData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PointDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PointData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *经度
     * </pre>
     *
     * <code>double lng = 1;</code>
     */
    double getLng();

    /**
     * <pre>
     *纬度
     * </pre>
     *
     * <code>double lat = 2;</code>
     */
    double getLat();

    /**
     * <pre>
     *高度
     * </pre>
     *
     * <code>uint32 height = 3;</code>
     */
    int getHeight();
  }
  /**
   * Protobuf type {@code PointData}
   */
  public  static final class PointData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PointData)
      PointDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PointData.newBuilder() to construct.
    private PointData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PointData() {
      lng_ = 0D;
      lat_ = 0D;
      height_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PointData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              lng_ = input.readDouble();
              break;
            }
            case 17: {

              lat_ = input.readDouble();
              break;
            }
            case 24: {

              height_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TelemetryDataPB.internal_static_PointData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TelemetryDataPB.internal_static_PointData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PointData.class, Builder.class);
    }

    public static final int LNG_FIELD_NUMBER = 1;
    private double lng_;
    /**
     * <pre>
     *经度
     * </pre>
     *
     * <code>double lng = 1;</code>
     */
    public double getLng() {
      return lng_;
    }

    public static final int LAT_FIELD_NUMBER = 2;
    private double lat_;
    /**
     * <pre>
     *纬度
     * </pre>
     *
     * <code>double lat = 2;</code>
     */
    public double getLat() {
      return lat_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 3;
    private int height_;
    /**
     * <pre>
     *高度
     * </pre>
     *
     * <code>uint32 height = 3;</code>
     */
    public int getHeight() {
      return height_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (lng_ != 0D) {
        output.writeDouble(1, lng_);
      }
      if (lat_ != 0D) {
        output.writeDouble(2, lat_);
      }
      if (height_ != 0) {
        output.writeUInt32(3, height_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (lng_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, lng_);
      }
      if (lat_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, lat_);
      }
      if (height_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, height_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PointData)) {
        return super.equals(obj);
      }
      PointData other = (PointData) obj;

      boolean result = true;
      result = result && (
          Double.doubleToLongBits(getLng())
          == Double.doubleToLongBits(
              other.getLng()));
      result = result && (
          Double.doubleToLongBits(getLat())
          == Double.doubleToLongBits(
              other.getLat()));
      result = result && (getHeight()
          == other.getHeight());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LNG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLng()));
      hash = (37 * hash) + LAT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLat()));
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PointData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PointData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PointData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PointData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PointData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PointData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PointData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PointData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PointData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PointData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PointData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PointData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PointData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PointData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PointData)
        PointDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TelemetryDataPB.internal_static_PointData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TelemetryDataPB.internal_static_PointData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PointData.class, Builder.class);
      }

      // Construct using TelemetryDataPB.PointData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        lng_ = 0D;

        lat_ = 0D;

        height_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TelemetryDataPB.internal_static_PointData_descriptor;
      }

      public PointData getDefaultInstanceForType() {
        return PointData.getDefaultInstance();
      }

      public PointData build() {
        PointData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PointData buildPartial() {
        PointData result = new PointData(this);
        result.lng_ = lng_;
        result.lat_ = lat_;
        result.height_ = height_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PointData) {
          return mergeFrom((PointData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PointData other) {
        if (other == PointData.getDefaultInstance()) return this;
        if (other.getLng() != 0D) {
          setLng(other.getLng());
        }
        if (other.getLat() != 0D) {
          setLat(other.getLat());
        }
        if (other.getHeight() != 0) {
          setHeight(other.getHeight());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PointData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PointData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double lng_ ;
      /**
       * <pre>
       *经度
       * </pre>
       *
       * <code>double lng = 1;</code>
       */
      public double getLng() {
        return lng_;
      }
      /**
       * <pre>
       *经度
       * </pre>
       *
       * <code>double lng = 1;</code>
       */
      public Builder setLng(double value) {
        
        lng_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *经度
       * </pre>
       *
       * <code>double lng = 1;</code>
       */
      public Builder clearLng() {
        
        lng_ = 0D;
        onChanged();
        return this;
      }

      private double lat_ ;
      /**
       * <pre>
       *纬度
       * </pre>
       *
       * <code>double lat = 2;</code>
       */
      public double getLat() {
        return lat_;
      }
      /**
       * <pre>
       *纬度
       * </pre>
       *
       * <code>double lat = 2;</code>
       */
      public Builder setLat(double value) {
        
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *纬度
       * </pre>
       *
       * <code>double lat = 2;</code>
       */
      public Builder clearLat() {
        
        lat_ = 0D;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <pre>
       *高度
       * </pre>
       *
       * <code>uint32 height = 3;</code>
       */
      public int getHeight() {
        return height_;
      }
      /**
       * <pre>
       *高度
       * </pre>
       *
       * <code>uint32 height = 3;</code>
       */
      public Builder setHeight(int value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *高度
       * </pre>
       *
       * <code>uint32 height = 3;</code>
       */
      public Builder clearHeight() {
        
        height_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PointData)
    }

    // @@protoc_insertion_point(class_scope:PointData)
    private static final PointData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PointData();
    }

    public static PointData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PointData>
        PARSER = new com.google.protobuf.AbstractParser<PointData>() {
      public PointData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PointData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PointData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PointData> getParserForType() {
      return PARSER;
    }

    public PointData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TelemetryData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TelemetryData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlanLineData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlanLineData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PointData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PointData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026TelemetryDataBuf.proto\"\277\001\n\rTelemetryDa" +
      "ta\022\013\n\003lng\030\001 \001(\001\022\013\n\003lat\030\002 \001(\001\022\020\n\010altitude" +
      "\030\003 \001(\002\022\022\n\nultrasonic\030\004 \001(\002\022\r\n\005pitch\030\005 \001(" +
      "\002\022\014\n\004roll\030\006 \001(\002\022\013\n\003yaw\030\007 \001(\002\022\020\n\010airspeed" +
      "\030\010 \001(\002\022\020\n\010velocity\030\t \001(\002\022\021\n\ttimestamp\030\n " +
      "\001(\004\022\r\n\005boxSn\030\013 \001(\t\"g\n\014PlanLineData\022\026\n\016fi" +
      "nishedAction\030\001 \001(\r\022\020\n\010maxSpeed\030\002 \001(\002\022\021\n\t" +
      "autoSpeed\030\003 \001(\002\022\032\n\006points\030\004 \003(\0132\n.PointD" +
      "ata\"5\n\tPointData\022\013\n\003lng\030\001 \001(\001\022\013\n\003lat\030\002 \001" +
      "(\001\022\016\n\006height\030\003 \001(\rB8\n%com.tyjw.uav.platf",
      "orm.common.protobufB\017TelemetryDataPBb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TelemetryData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TelemetryData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TelemetryData_descriptor,
        new String[] { "Lng", "Lat", "Altitude", "Ultrasonic", "Pitch", "Roll", "Yaw", "Airspeed", "Velocity", "Timestamp", "BoxSn", });
    internal_static_PlanLineData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PlanLineData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlanLineData_descriptor,
        new String[] { "FinishedAction", "MaxSpeed", "AutoSpeed", "Points", });
    internal_static_PointData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PointData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PointData_descriptor,
        new String[] { "Lng", "Lat", "Height", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
